version: '3.8'

services:
  # Base de datos MariaDB
  database:
    image: mariadb:10.11
    container_name: colombianet-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: colombianet
      MYSQL_USER: colombianet_user
      MYSQL_PASSWORD: colombianet_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - colombianet-network

  # Backend (Node.js/Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: colombianet-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: colombianet
      DB_USER: colombianet_user
      DB_PASSWORD: colombianet_password
      JWT_SECRET: your-secret-key-here
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - colombianet-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: colombianet-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - colombianet-network

volumes:
  db_data:
    driver: local

networks:
  colombianet-network:
    driver: bridge